# image: Ubuntu1804  # образ для сборки
# stack: node 10  # окружение
# branches:
# only:
# - master # ветка git
# cache: node_modules # кеширование install:
# - yarn add # команда установки зависимостей build: off
# build_script:
# - yarn run build # команда сборки test_script:
# - yarn run lint && yarn test # скрипт тестирования deploy_script: # скрипт развёртывания
# - git config --global credential.helper store
# - git config --global user.name AppVeyor
# - git config --global user.email ci@appveyor.com
# - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials" - npx push-dir --dir=dist --branch=gh-pages --force --verbose

branches:
  only:
    - webpack-4
    - master
    - next
    - dev-1

init:
  - git config --global core.autocrlf input

cache:
  - "..\\.yarn-cache"
  - ".jest-cache"

install:
  - ps: Install-Product node 12 x64
  - yarn --frozen-lockfile --preferred-cache-folder ..\\.yarn-cache
  - yarn link --frozen-lockfile --preferred-cache-folder ..\\.yarn-cache || yarn link --frozen-lockfile --preferred-cache-folder ..\\.yarn-cache
  - yarn link webpack --frozen-lockfile --preferred-cache-folder ..\\.yarn-cache

build: off

matrix:
  fast_finish: true

test_script:
  - node --version
  - yarn --version
  - cmd: set JEST=--maxWorkers=2 --cacheDirectory .jest-cache
  - cmd: yarn appveyor:integration
  - cmd: yarn istanbul report --report lcovonly
  - cmd: yarn unlink webpack
  - cmd: yarn global add codecov && codecov -F integration --disable=gcov
  - cmd: del /F /Q .jest-cache\\haste-map* .jest-cache\\perf-cache* 2> null || Ver > null